// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB_Gif-ww5H89iNQRHdN9kYHTCHeY1D_Aw",
    authDomain: "esp32-fe88b.firebaseapp.com",
    databaseURL:
        "https://esp32-fe88b-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "esp32-fe88b",
    storageBucket: "esp32-fe88b.firebasestorage.app",
    messagingSenderId: "787884523949",
    appId: "1:787884523949:web:5b43af2a6912f2e33ca124",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB_Gif-ww5H89iNQRHdN9kYHTCHeY1D_Aw",
    appId: "1:787884523949:android:5b43af2a6912f2e33ca124",
    messagingSenderId: "787884523949",
    projectId: "esp32-fe88b",
    databaseURL: "https://esp32-fe88b-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: "esp32-fe88b.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'agriadvisor-ai',
    storageBucket: 'agriadvisor-ai.appspot.com',
    iosBundleId: 'com.agriadvisor.app.agriapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'agriadvisor-ai',
    storageBucket: 'agriadvisor-ai.appspot.com',
    iosBundleId: 'com.agriadvisor.app.agriapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: '1:123456789:web:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'agriadvisor-ai',
    authDomain: 'agriadvisor-ai.firebaseapp.com',
    storageBucket: 'agriadvisor-ai.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
